# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-26 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20180326_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
